-- Bab 19: Studi Kasus SPK - Skema DDL
DROP TABLE IF EXISTS PENILAIAN;
DROP TABLE IF EXISTS PESERTA_KELAS;
DROP TABLE IF EXISTS KELAS;
DROP TABLE IF EXISTS KRITERIA_PENILAIAN;
DROP TABLE IF EXISTS PERIODE;
DROP TABLE IF EXISTS MATA_KULIAH;
DROP TABLE IF EXISTS MAHASISWA;
DROP TABLE IF EXISTS DOSEN;

CREATE TABLE DOSEN (Id_Dosen CHAR(3) PRIMARY KEY, Nama_Dosen VARCHAR(100) NOT NULL);
CREATE TABLE MAHASISWA (NIM CHAR(4) PRIMARY KEY, Nama_Mahasiswa VARCHAR(100) NOT NULL);
CREATE TABLE MATA_KULIAH (Kode_MK CHAR(4) PRIMARY KEY, Nama_MK VARCHAR(100) NOT NULL, SKS INT NOT NULL);
CREATE TABLE PERIODE (Id_Periode INT PRIMARY KEY, Nama_Periode VARCHAR(50) NOT NULL, Tgl_Mulai DATE NOT NULL, Tgl_Selesai DATE NOT NULL);
CREATE TABLE KRITERIA_PENILAIAN (Id_Kriteria CHAR(2) PRIMARY KEY, Nama_Kriteria VARCHAR(100) NOT NULL);
CREATE TABLE KELAS (Id_Kelas INT PRIMARY KEY, Id_Periode INT NOT NULL, Kode_MK CHAR(4) NOT NULL, Id_Dosen CHAR(3) NOT NULL, FOREIGN KEY (Id_Periode) REFERENCES PERIODE(Id_Periode), FOREIGN KEY (Kode_MK) REFERENCES MATA_KULIAH(Kode_MK), FOREIGN KEY (Id_Dosen) REFERENCES DOSEN(Id_Dosen));
CREATE TABLE PESERTA_KELAS (Id_Peserta INT PRIMARY KEY, Id_Kelas INT NOT NULL, NIM CHAR(4) NOT NULL, FOREIGN KEY (Id_Kelas) REFERENCES KELAS(Id_Kelas), FOREIGN KEY (NIM) REFERENCES MAHASISWA(NIM));
CREATE TABLE PENILAIAN (Id_Penilaian INT PRIMARY KEY, Id_Peserta INT NOT NULL, Id_Kriteria CHAR(2) NOT NULL, Skor INT NOT NULL, FOREIGN KEY (Id_Peserta) REFERENCES PESERTA_KELAS(Id_Peserta), FOREIGN KEY (Id_Kriteria) REFERENCES KRITERIA_PENILAIAN(Id_Kriteria), CONSTRAINT chk_skor CHECK (Skor >= 1 AND Skor <= 5));